[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
test1 = "F51kSctUgWPRt2pRKoXZ6txLJwRfvkBb3tkxFtVzRv8x"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/ayad/.config/solana/id3.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
